# -*- coding: utf-8 -*-
"""LanguageTranslationTool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snuI3GFXWoiDEvHGwwybVRD29EVrxSYP
"""

!pip install googletrans==4.0.0-rc1

from googletrans import Translator, LANGUAGES

def translate_text(text, source_language, target_language):
    """
    Translates text from the source language to the target language using googletrans library.

    Args:
    text (str): The text to be translated.
    source_language (str): The language code of the source language, e.g., 'en' for English.
    target_language (str): The language code of the target language, e.g., 'es' for Spanish.

    Returns:
    tuple: The translated text and its Romanized form (if available).
    """
    translator = Translator()
    translation = translator.translate(text, src=source_language, dest=target_language)
    translated_text = translation.text
    romanized_text = translation.pronunciation if translation.pronunciation else "\n\nRomanization not available"
    return translated_text, romanized_text

while True:
   # Get the text to be translated from the user
   source_text = input("Enter the text to be translated: ")

   # Display available languages
   print("\nAvailable languages and their codes:\n")
   for code, language in LANGUAGES.items():
       print(f"{code}: {language}")

   # Get the source and target language codes from the user
   source_language = input("\nEnter the source language code: ").strip()
   target_language = input("Enter the target language code: ").strip()

   # Validate the language codes
   if source_language not in LANGUAGES:
       print("Invalid source language code. Please try again.")
   elif target_language not in LANGUAGES:
       print("Invalid target language code. Please try again.")
   else:
       # Translate the text
       translated_text, romanized_text = translate_text(source_text, source_language, target_language)
       print(f"\nTranslated text: {translated_text}")
       print(f"Romanized text: {romanized_text}")

       # Ask the user if they want to translate another text
       translate_again = input("\nDo you want to translate another text? (yes/no): ").strip().lower()
       if translate_again != "yes":
           break


print("\n\nTranslation process ended....")